"""enforce one wind-up per day

Revision ID: 2711da7f5aad
Revises: 2250bd077d9a
Create Date: 2026-07-25 21:56:30.962621
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '2711da7f5aad'
down_revision: str | None = '2250bd077d9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_xp_events_wind_up_per_day', 'xp_events', ['user_id', 'happened_on'], unique=True, postgresql_where=sa.text("source = 'wind_up'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_xp_events_wind_up_per_day', table_name='xp_events', postgresql_where=sa.text("source = 'wind_up'"))
    # ### end Alembic commands ###
